# Generated by Django 5.1.1 on 2024-10-10 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_layers', '0005_languagemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_completions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('completions_target_number', models.IntegerField(default=30)),
                ('target_model_description', models.TextField()),
                ('source_text', models.TextField()),
                ('generation_prompt', models.TextField(default='\nYou are an specialist machine learning engineer.\nYou are in charge of generating a set of {{self.completions_target_number}} completions to train an AI model.\n\nAfter the finetuning or  training process the target model should be like:\n---\n{{self.target_model_description}}\n---\n\n\nUse this text as a source of information to generate the completions:\n---\n{{self.source_text}}\n---\n\nonly_prompt = {{self.only_prompt}}\n\nIf the variable only_prompt is True, then you must generate only the prompt for each completion, otherwise generate the prompt and the answer.\n\n\n')),
                ('only_prompt', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_generators', to=settings.AUTH_USER_MODEL)),
                ('generation_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_layers.languagemodel')),
            ],
        ),
    ]
