# Generated by Django 5.1.1 on 2024-10-28 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_layers', '0009_agent_llm'),
        ('finetuning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completion',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_layers.agent'),
        ),
        migrations.AlterField(
            model_name='traininggenerator',
            name='generation_prompt',
            field=models.TextField(default='\nYou are an specialist machine learning engineer.\nYou are in charge of generating a set of {completions_target_number} completions to train an AI model.\n\nAfter the finetuning or  training process the target model should be like:\n---\n{target_model_description}\n---\n\n\nUse this text as a source of information to generate the completions:\n---\n{source_text}\n---\n\nonly_prompt = {only_prompt}\n\nIf the variable only_prompt is True, then you must generate only the prompt for each completion, otherwise generate the prompt and the answer.\n'),
        ),
    ]
