# Generated by Django 5.1.1 on 2024-10-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finetuning', '0005_completion_training_generator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininggenerator',
            name='generation_prompt',
            field=models.TextField(default='\nYou are an specialist machine learning engineer.\nYou are in charge of generating a set of {completions_target_number} completions to train an AI model.\n\nAfter the finetuning or  training process the target model should be like:\n---\n{target_model_description}\n---\n\n\nUse this text as a source of information to generate the completions:\n---\n{source_text}\n---\n\nonly_prompt = {only_prompt}\n\nIf the variable only_prompt is True, then you must generate only the prompt for each completion, otherwise generate the prompt and the answer.\n\n\nCLARIFICATION:\nThe goal is to optain a list of different completions based in the source text. Each prompt/answer pair must be different from the others.\n'),
        ),
    ]
