# Generated by Django 5.1.1 on 2026-05-26 22:21

import api.finetuning.context_rules
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finetuning', '0009_completion_assignments_context_rules'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='completion',
            new_name='finetuning__approve_ddd2f8_idx',
            old_name='finetuning__approve_2d8e01_idx',
        ),
        migrations.RenameIndex(
            model_name='completionassignment',
            new_name='finetuning__agent_i_2ff813_idx',
            old_name='finetuning__agent_i_8f3c2a_idx',
        ),
        migrations.RenameIndex(
            model_name='completionassignment',
            new_name='finetuning__complet_68c3b9_idx',
            old_name='finetuning__complet_91a4b1_idx',
        ),
        migrations.AlterField(
            model_name='completion',
            name='context_rules',
            field=models.JSONField(default=api.finetuning.context_rules.default_context_rules_dict),
        ),
    ]
