"""
++Django settings for api project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-=4jp(5z$n=dr10)4(0vl4i+wuww4ijwxd&%@0^gt9bbp^+k-(q'
SECRET_KEY = os.environ.get("SECRET_KEY", default="secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
# Default to False unless explicitly enabled via env.
DEBUG = os.environ.get("DEBUG", "false").strip().lower() in {"1", "true", "yes", "on"}

# settings.py
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
]


# Extra hosts from env (comma-separated, e.g. masscer-ai.ngrok.app,your-domain.com).
# Prefer ALLOWED_EXTRA_HOSTS to match infra config, keep ALLOWED_HOSTS as fallback.
_allowed_hosts_env = os.environ.get("ALLOWED_EXTRA_HOSTS") or os.environ.get(
    "ALLOWED_HOSTS", ""
)
_allowed_extra_hosts = [
    h.strip() for h in _allowed_hosts_env.split(",") if h.strip()
]
if _allowed_hosts_env:
    ALLOWED_HOSTS.extend(_allowed_extra_hosts)

# Trusted origins for CSRF-protected endpoints (e.g. Django admin login over ngrok).
CSRF_TRUSTED_ORIGINS = [
    "http://localhost",
    "http://127.0.0.1",
]
# Reuse ALLOWED_EXTRA_HOSTS by deriving common origin schemes.
for host in _allowed_extra_hosts:
    CSRF_TRUSTED_ORIGINS.append(f"https://{host}")
    CSRF_TRUSTED_ORIGINS.append(f"http://{host}")

_csrf_trusted_origins_env = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
if _csrf_trusted_origins_env:
    CSRF_TRUSTED_ORIGINS.extend(
        origin.strip()
        for origin in _csrf_trusted_origins_env.split(",")
        if origin.strip()
    )

# Keep order stable while removing duplicates.
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "django_celery_beat",
    "django_celery_results",
    "api.authenticate",
    "api.providers",
    "api.ai_layers",
    "api.messaging",
    "api.rag",
    "api.finetuning",
    "api.tools",
    "api.whatsapp",
    "api.feedback",
    "api.preferences",
    "api.prompting",
    "api.notify",
    "api.generations",
    "api.payments",
    "api.consumption",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "api.wsgi.application"

CORS_ALLOW_ALL_ORIGINS = True

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:8001",
# ]


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get("DB_CONNECTION_STRING", "sqlite:///db.sqlite3"),
        conn_max_age=0,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

DATA_UPLOAD_MAX_MEMORY_SIZE = 41943040
FILE_UPLOAD_MAX_MEMORY_SIZE = 41943040
# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATIC_URL = 'static/'
STATIC_URL = "/static/"


STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = "django-db"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"

CELERY_RESULT_EXPIRES = 3600

# Celery Beat Configuration
# Using beat_schedule in celery.py instead of DatabaseScheduler
# CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"


MEDIA_ROOT = os.environ.get("MEDIA_ROOT", os.path.join(BASE_DIR, "media"))
MEDIA_URL = "/media/"
# Base URL for building absolute URLs (e.g. for MessageAttachment display).
# Set API_BASE_URL in env for production (e.g. https://api.example.com).
API_BASE_URL = os.environ.get("API_BASE_URL", "")


if not os.path.exists(MEDIA_ROOT):
    os.makedirs(MEDIA_ROOT)


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_CACHE_URL", "redis://localhost:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "KEY_PREFIX": "chat_cache",
    }
}


FIRECRAWL_API_KEY = os.environ.get("FIRECRAWL_API_KEY", "")

# CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"