# Generated by Django 5.1.1 on 2026-07-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthclient',
            name='grant_types',
            field=models.JSONField(blank=True, default=list, help_text='Allowed grant types, e.g. authorization_code, refresh_token'),
        ),
    ]
