# Generated by Django 5.1.1 on 2026-04-16 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_subject', models.CharField(db_index=True, help_text="OpenID Connect 'sub' for the Google account (stable id).", max_length=255)),
                ('google_email', models.CharField(blank=True, default='', help_text='Google account email for display.', max_length=255)),
                ('access_token', models.TextField(help_text='OAuth 2.0 access token (short-lived).')),
                ('refresh_token', models.TextField(blank=True, default='', help_text='OAuth 2.0 refresh token; empty if not issued or stripped on re-auth.')),
                ('token_type', models.CharField(default='Bearer', max_length=32)),
                ('access_token_expires_at', models.DateTimeField(blank=True, help_text='UTC expiry of access_token; refresh before Drive API calls when set.', null=True)),
                ('scopes', models.TextField(blank=True, default='', help_text='Granted OAuth scopes (e.g. space-separated), for UI and permission checks.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('needs_reauth', 'Needs re-authentication')], default='active', max_length=20)),
                ('last_token_error', models.TextField(blank=True, default='', help_text='Last token refresh or auth error message (truncated in app code if needed).')),
                ('default_upload_folder_id', models.CharField(blank=True, default='', help_text='Drive file id of the folder used as default for uploads.', max_length=255)),
                ('default_upload_folder_name', models.CharField(blank=True, default='', help_text='Cached display name of default_upload_folder_id.', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_drive_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Drive connection',
                'verbose_name_plural': 'Google Drive connections',
            },
        ),
    ]
