# Generated by Django 5.1.1 on 2026-06-12 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0023_organizationmanagementproxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google_drive', 'Google Drive')], max_length=64)),
                ('access_token', models.TextField(help_text='OAuth access token.')),
                ('refresh_token', models.TextField(blank=True, default='', help_text='OAuth refresh token (used to obtain a new access token).')),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, help_text='UTC datetime when the access_token expires. Null = non-expiring.', null=True)),
                ('scopes', models.TextField(blank=True, default='', help_text='Space-separated OAuth scopes granted at connect time.')),
                ('account_email', models.CharField(blank=True, default='', help_text='Email of the connected third-party account.', max_length=255)),
                ('account_label', models.CharField(blank=True, default='', help_text='Display label for the connected account.', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='authenticate.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration',
                'verbose_name_plural': 'Integrations',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('user__isnull', False)), models.Q(('organization__isnull', False), ('user__isnull', True)), _connector='OR'), name='integration_exactly_one_owner'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'provider'), name='integration_unique_user_provider'), models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'provider'), name='integration_unique_organization_provider')],
            },
        ),
    ]
