# Generated by Django 5.1.1 on 2026-03-23 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscriptionplan_subscription_subscriptionpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='credits_limit',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='credits_limit',
        ),
        migrations.AddField(
            model_name='subscription',
            name='credits_limit_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Override the plan's default credit budget (in USD) for this subscription.", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='credits_limit_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Credit budget in USD included in this plan. Leave blank for unlimited.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
