# Generated by Django 5.1.1 on 2026-05-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_subscription_enterprise_deal_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='slug',
            field=models.CharField(choices=[('free_trial', 'Free Trial'), ('pay_as_you_go', 'Pay As You Go'), ('organization', 'Organization'), ('custom', 'Custom')], max_length=50, unique=True),
        ),
    ]
