# Generated by Django 5.1.1 on 2026-09-17 19:47

import api.org_lists.models
import api.org_lists.schemas
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0029_organization_pld_access_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to=api.org_lists.models.organization_list_upload_to)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=api.org_lists.schemas.default_config_dict)),
                ('import_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('import_error', models.TextField(blank=True, default='')),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_lists', to='authenticate.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_lists_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationListRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('search_document', models.TextField(blank=True, default='')),
                ('organization_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='org_lists.organizationlist')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='organizationlist',
            index=models.Index(fields=['organization', '-created_at'], name='org_lists_o_organiz_0f13c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationlistrecord',
            constraint=models.UniqueConstraint(fields=('organization_list', 'position'), name='unique_org_list_record_position'),
        ),
    ]
