# Generated by Django 5.1.1 on 2025-01-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogeneration',
            name='file_path',
        ),
        migrations.AddField(
            model_name='videogeneration',
            name='engine',
            field=models.CharField(choices=[('runway', 'Runway')], default='runway', max_length=255),
        ),
        migrations.AddField(
            model_name='videogeneration',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='generations/videos'),
        ),
    ]
