# Generated by Django 5.1.1 on 2024-10-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_layers', '0003_alter_agent_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='model_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('ollama', 'Ollama'), ('anthropic', 'Anthropic')], default='openai', max_length=20),
        ),
        migrations.AlterField(
            model_name='agent',
            name='model_slug',
            field=models.CharField(blank=True, default='gpt-4o-mini', max_length=100, null=True),
        ),
    ]
