# Generated by Django 5.1.1 on 2024-10-14 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_layers', '0006_agent_default'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelConfig',
        ),
        migrations.AddField(
            model_name='agent',
            name='frequency_penalty',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-2.0), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AddField(
            model_name='agent',
            name='max_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='presence_penalty',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-2.0), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AddField(
            model_name='agent',
            name='temperature',
            field=models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AddField(
            model_name='agent',
            name='top_p',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
