# Generated by Django 5.1.1 on 2024-10-14 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_layers', '0007_delete_modelconfig_agent_frequency_penalty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='frequency_penalty',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-2.0), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AlterField(
            model_name='agent',
            name='max_tokens',
            field=models.IntegerField(blank=True, default=4000, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='presence_penalty',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-2.0), django.core.validators.MaxValueValidator(2.0)]),
        ),
    ]
