# Generated by Django 5.1.1 on 2024-11-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_layers', '0010_agent_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
