# Generated by Django 5.1.1 on 2024-11-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_layers', '0011_alter_agent_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='openai_voice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
