# Generated by Django 5.1.1 on 2024-11-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_layers', '0013_alter_agent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
