# Generated by Django 5.1.1 on 2025-01-13 19:26

import api.ai_layers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_layers', '0017_alter_languagemodel_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagemodel',
            name='pricing',
            field=models.JSONField(default=api.ai_layers.models.default_pricing),
        ),
    ]
