# Generated by Django 5.1.1 on 2026-01-06 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_layers', '0019_agent_conversation_title_prompt'),
        ('authenticate', '0015_role_roleassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this agent belongs to. If set, all members of the organization can use it.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='authenticate.organization'),
        ),
    ]
