# Generated by Django 5.1.1 on 2026-02-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_layers', '0020_agent_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagemodel',
            name='is_reasoning_model',
            field=models.BooleanField(default=False),
        ),
    ]
