# Generated by Django 5.1.1 on 2026-03-14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_layers", "0022_agentsession"),
        ("authenticate", "0015_role_roleassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleAgentAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        default=uuid.uuid4,
                        editable=False,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_access_assignments",
                        to="ai_layers.agent",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_access_assignments",
                        to="authenticate.role",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agent",
            name="allowed_roles",
            field=models.ManyToManyField(
                blank=True,
                help_text="If empty, all organization members can access this agent. If set, only users with any of these roles (or the org owner) can access it.",
                related_name="agents_with_access",
                through="ai_layers.RoleAgentAssignment",
                to="authenticate.role",
            ),
        ),
        migrations.AddConstraint(
            model_name="roleagentassignment",
            constraint=models.UniqueConstraint(
                fields=("role", "agent"),
                name="unique_role_agent_access",
            ),
        ),
    ]

