# Generated by Django 5.1.1 on 2026-05-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_layers', '0023_agent_role_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='model_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('google', 'Google'), ('ollama', 'Ollama'), ('anthropic', 'Anthropic')], default='openai', max_length=20),
        ),
    ]
