# Generated by Django 5.1.1 on 2026-07-10 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_layers', '0026_agent_kind_platform_assistant'),
        ('voices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='openai_voice',
        ),
        migrations.AddField(
            model_name='agent',
            name='default_voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='voices.voice'),
        ),
    ]
