# Generated by Django 5.1.1 on 2026-08-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_layers', '0029_mcpclient_allowed_tool_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='pre_approved_tools',
            field=models.JSONField(blank=True, default=list, help_text='Tool names used to pre-fill tool selection when this agent is picked in the main chat. Not enforced server-side — the user can still toggle tools freely per message; edit this list here to change the default.'),
        ),
    ]
