# Generated by Django 5.1.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_layers", "0030_agent_pre_approved_tools"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text=(
                    "Short specialty description for humans and other agents "
                    "(e.g. list_agents / handoff). Not injected into the system prompt."
                ),
            ),
        ),
    ]
