# Generated by Django 5.1.1 on 2026-08-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_layers', '0031_agent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='pre_approved_tools',
            field=models.JSONField(blank=True, default=list, help_text='Tool names this agent may use in main chat and scheduled runs. Source of truth for web chat (and schedules); channel surfaces (WhatsApp / widget / MCP) keep their own capability lists.'),
        ),
    ]
