# Generated by Django migration (manual)

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import api.document_templates.models as document_templates_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authenticate", "0022_rename_authentica_organiz_a772fc_idx_authenticat_organiz_96db20_idx_and_more"),
        ("ai_layers", "0024_alter_agent_model_provider"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "file",
                    models.FileField(upload_to=document_templates_models.document_template_upload_to),
                ),
                ("original_filename", models.CharField(blank=True, default="", max_length=255)),
                ("file_size", models.PositiveIntegerField(default=0)),
                (
                    "content_type",
                    models.CharField(
                        default="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                        max_length=128,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Shape: {"placeholders": [...], "variables": {name: {description, required, example}}}',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_templates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_templates",
                        to="authenticate.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentDocumentTemplateAssignment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "usage_instructions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="When and how the AI should use this template for this agent.",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_template_assignments",
                        to="ai_layers.agent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_template_assignments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_assignments",
                        to="document_templates.documenttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="agentdocumenttemplateassignment",
            constraint=models.UniqueConstraint(
                fields=("agent", "template"),
                name="document_templates_unique_agent_template",
            ),
        ),
    ]
