# Generated by Django 5.1.1 on 2026-09-01 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_pld_entity_expedient'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='compliancefolio',
            new_name='compliance__organiz_97edcb_idx',
            old_name='compliance__organiz_folio_idx',
        ),
        migrations.RenameIndex(
            model_name='foliodocument',
            new_name='compliance__folio_i_60a03d_idx',
            old_name='compliance__folio_d_status_idx',
        ),
        migrations.RenameIndex(
            model_name='folioevent',
            new_name='compliance__folio_i_57b488_idx',
            old_name='compliance__folio_e_type_idx',
        ),
        migrations.RenameIndex(
            model_name='pldentity',
            new_name='compliance__organiz_bb5576_idx',
            old_name='compliance_pld_ent_org_rel',
        ),
        migrations.RenameIndex(
            model_name='pldexpedient',
            new_name='compliance__organiz_525631_idx',
            old_name='compliance_pld_exp_org_st',
        ),
    ]
