# Generated by Django 5.1.1 on 2026-09-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_pldentity_email_pldinvite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pldinvite',
            new_name='compliance__organiz_f4c259_idx',
            old_name='compliance__organiz_pldinv_idx',
        ),
        migrations.RenameIndex(
            model_name='pldinvite',
            new_name='compliance__email_e467ab_idx',
            old_name='compliance__email_pldinv_idx',
        ),
    ]
