# Generated by Django 5.2.4 on 2026-09-07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0009_pldexpedient_prequalification"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchlistSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "list_slug",
                    models.CharField(
                        choices=[("onu_csnu", "ONU CSNU consolidated")],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("source_url", models.URLField(max_length=512)),
                ("file_sha256", models.CharField(db_index=True, max_length=64)),
                ("content_length", models.PositiveIntegerField(default=0)),
                (
                    "date_generated",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Source dateGenerated (or equivalent) from the list file.",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("succeeded", "Succeeded"), ("failed", "Failed")],
                        default="succeeded",
                        max_length=16,
                    ),
                ),
                ("is_current", models.BooleanField(db_index=True, default=False)),
                ("record_count", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True, default="")),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Watchlist snapshot",
                "verbose_name_plural": "Watchlist snapshots",
                "ordering": ["-ingested_at"],
            },
        ),
        migrations.CreateModel(
            name="WatchlistRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("entity", "Entity"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("reference_number", models.CharField(db_index=True, max_length=64)),
                ("data_id", models.CharField(blank=True, default="", max_length=32)),
                ("primary_name", models.CharField(blank=True, default="", max_length=512)),
                ("listed_on", models.CharField(blank=True, default="", max_length=32)),
                ("names", models.JSONField(blank=True, default=list)),
                ("dates_of_birth", models.JSONField(blank=True, default=list)),
                ("document_numbers", models.JSONField(blank=True, default=list)),
                ("nationalities", models.JSONField(blank=True, default=list)),
                (
                    "search_document",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Folded searchable blob of names, aliases, IDs, and notes.",
                    ),
                ),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="compliance.watchlistsnapshot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Watchlist record",
                "verbose_name_plural": "Watchlist records",
                "ordering": ["reference_number"],
            },
        ),
        migrations.AddIndex(
            model_name="watchlistsnapshot",
            index=models.Index(
                fields=["list_slug", "-ingested_at"],
                name="compliance__list_sl_9f3a21_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="watchlistsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("list_slug",),
                name="unique_current_watchlist_snapshot_per_list",
            ),
        ),
        migrations.AddIndex(
            model_name="watchlistrecord",
            index=models.Index(
                fields=["snapshot", "record_type"],
                name="compliance__snapsho_4c1e8a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="watchlistrecord",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "reference_number"),
                name="unique_watchlist_record_per_snapshot_ref",
            ),
        ),
    ]
