# Generated by Django 5.1.1 on 2026-09-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0010_watchlist_snapshot_record'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='watchlistrecord',
            new_name='compliance__snapsho_47cfbf_idx',
            old_name='compliance__snapsho_4c1e8a_idx',
        ),
        migrations.RenameIndex(
            model_name='watchlistsnapshot',
            new_name='compliance__list_sl_3170c8_idx',
            old_name='compliance__list_sl_9f3a21_idx',
        ),
    ]
