# Generated by Django 5.1.1 on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0011_rename_compliance__snapsho_4c1e8a_idx_compliance__snapsho_47cfbf_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlistsnapshot",
            name="list_slug",
            field=models.CharField(
                choices=[
                    ("onu_csnu", "ONU CSNU consolidated"),
                    ("sat_69b", "SAT Art. 69-B complete"),
                    ("sat_69b_bis", "SAT Art. 69-B Bis complete"),
                    ("sat_69_firmes", "SAT Art. 69 firmes"),
                    ("sat_69_no_localizados", "SAT Art. 69 no localizados"),
                    ("sat_69_exigibles", "SAT Art. 69 exigibles"),
                    ("sat_69_sentencias", "SAT Art. 69 sentencias"),
                    ("sat_69_csd", "SAT Art. 69 CSD sin efectos"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
