# Generated by Django 5.1.1 on 2026-09-07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0012_watchlistsnapshot_sat_list_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="pldexpedient",
            name="screening_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="pldexpedient",
            name="screening_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="pldexpedient",
            name="screened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PLDClarificationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("identification", "Identification"),
                            ("screening", "Screening"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("prompt", models.CharField(max_length=400)),
                (
                    "answer_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("document", "Document"),
                            ("either", "Text or document"),
                        ],
                        default="text",
                        max_length=16,
                    ),
                ),
                ("target", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("answered", "Answered"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                ("text_answer", models.TextField(blank=True, default="")),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expedient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clarification_requests",
                        to="compliance.pldexpedient",
                    ),
                ),
            ],
            options={
                "verbose_name": "PLD clarification request",
                "verbose_name_plural": "PLD clarification requests",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="pldclarificationrequest",
            index=models.Index(
                fields=["expedient", "stage", "status"],
                name="compliance__expedie_clar_idx",
            ),
        ),
    ]
