# Generated by Django 5.1.1 on 2026-09-07 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0013_clarification_and_screening'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pldclarificationrequest',
            new_name='compliance__expedie_f67682_idx',
            old_name='compliance__expedie_clar_idx',
        ),
    ]
