# Generated by Django 5.1.1 on 2026-09-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0016_pldexpedient_risk_gate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pldexpedient',
            name='risk_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='', max_length=16),
        ),
    ]
