# Generated by Django 5.1.1 on 2026-10-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0019_pldentity_ppe_screening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pldexpedient',
            name='ppe_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='', max_length=16),
        ),
    ]
