# Generated by Django 5.1.1 on 2024-09-21 22:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishableToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default='fbd224a8ed3b4f06a20cf472d5a0b723', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('duration_hours', models.IntegerField(blank=True, null=True)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
