# Generated by Django 5.1.1 on 2024-11-11 22:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_organization_organizationmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialsManager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('openai_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('brave_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('anthropic_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('pexels_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.organization')),
            ],
        ),
    ]
