# Generated by Django 5.1.1 on 2024-09-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_publishabletoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishabletoken',
            name='token',
            field=models.CharField(default='d14d0410e06e4baca841af270af61b75', max_length=255, unique=True),
        ),
    ]
