# Generated by Django 5.1.1 on 2024-11-11 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_credentialsmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='slug',
        ),
    ]
