# Generated by Django 5.1.1 on 2024-09-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_alter_publishabletoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishabletoken',
            name='token',
            field=models.CharField(default='b0c6662e32024875978ff567f667cc64', max_length=255, unique=True),
        ),
    ]
