# Generated by Django 5.1.1 on 2024-09-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_alter_publishabletoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishabletoken',
            name='token',
            field=models.CharField(default='cff941f1d45148a294cf3b629fce2158', max_length=255, unique=True),
        ),
    ]
