# Generated by Django 5.1.1 on 2024-09-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_alter_publishabletoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishabletoken',
            name='token',
            field=models.CharField(default='21e7b2a308a84530893575ac985b4790', max_length=255, unique=True),
        ),
    ]
