# Generated by Django 5.1.1 on 2025-12-08 17:58

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_credentialsmanager_elevenlabs_api_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('enabled', models.BooleanField(default=False)),
                ('feature_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='authenticate.featureflag')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization for organization-level feature flags. Leave blank for user-level flags.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_flag_assignments', to='authenticate.organization')),
                ('user', models.ForeignKey(blank=True, help_text='User for user-level feature flags. Leave blank for organization-level flags.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_flag_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Flag Assignment',
                'verbose_name_plural': 'Feature Flag Assignments',
                'constraints': [models.UniqueConstraint(condition=models.Q(('organization__isnull', False), ('user__isnull', True)), fields=('organization', 'feature_flag'), name='unique_organization_feature_flag'), models.UniqueConstraint(condition=models.Q(('organization__isnull', True), ('user__isnull', False)), fields=('user', 'feature_flag'), name='unique_user_feature_flag')],
            },
        ),
    ]
