# Generated by Django 5.1.1 on 2025-12-15 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0012_delete_organizationmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organización a la que pertenece el usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='authenticate.organization'),
        ),
    ]
