# Generated by Django 5.1.1 on 2026-01-07 19:09

import api.authenticate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0015_role_roleassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la organización (recomendado: 500x500px, formato PNG/JPG/SVG)', null=True, upload_to=api.authenticate.models.organization_logo_upload_path),
        ),
    ]
