# Generated by Django 5.1.1 on 2026-02-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0017_featureflag_organization_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the user is active within their organization. Deactivated users keep the org link but cannot access org resources.'),
        ),
    ]
