# Generated by Django 5.1.1 on 2024-09-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_collection_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
