# Generated by Django 5.1.1 on 2024-10-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0007_document_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='total_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
