# Generated by Django 5.1.1 on 2026-05-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0009_collection_owner_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='rag_documents/%Y/%m/'),
        ),
    ]
