# Generated by Django 5.1.1 on 2026-06-13 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('rag', '0011_remove_collection_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='drive_file_id',
            field=models.CharField(blank=True, db_index=True, help_text='Google Drive file ID when imported from Drive.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='drive_integration',
            field=models.ForeignKey(blank=True, help_text='Integration used to import/sync this document from Drive.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rag_documents', to='integrations.integration'),
        ),
        migrations.AddField(
            model_name='document',
            name='drive_modified_time',
            field=models.CharField(blank=True, default='', help_text='Drive modifiedTime at last import/sync (ISO string).', max_length=64),
        ),
    ]
