# Generated by Django 5.1.1 on 2026-08-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0026_userprofile__phone_numbers'),
        ('rag', '0013_document_visibility_acl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, help_text='When visibility is roles, users with any of these roles (or the org owner) can access.', related_name='rag_documents', to='authenticate.role'),
        ),
    ]
