# Generated by Django 5.1.1 on 2024-10-07 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_transcriptionjob_whisper_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('status_text', models.TextField(blank=True, null=True)),
                ('about', models.TextField()),
                ('duration', models.CharField(choices=[('LESS_THAN_MINUTE', 'Less than a minute'), ('MORE_THAN_MINUTE', 'More than a minute')], default='LESS_THAN_MINUTE', max_length=20)),
                ('orientation', models.CharField(choices=[('LANDSCAPE', 'Landscape'), ('PORTRAIT', 'Portrait'), ('SQUARE', 'Square')], default='LANDSCAPE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='generated_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_generation_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='tools.videogenerationjob')),
            ],
        ),
    ]
