# Generated by Django 5.1.1 on 2024-10-07 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_videogenerationjob_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech_text', models.TextField()),
                ('resource_query', models.TextField()),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('status_text', models.TextField(blank=True, null=True)),
                ('chunk_file', models.FileField(upload_to='video_chunks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='tools.video')),
            ],
        ),
    ]
