# Generated by Django 5.1.1 on 2024-10-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_videochunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='generated_videos/'),
        ),
        migrations.AlterField(
            model_name='videochunk',
            name='chunk_file',
            field=models.FileField(blank=True, null=True, upload_to='video_chunks/'),
        ),
    ]
