# Generated by Django 5.1.1 on 2025-01-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_alter_video_file_alter_videochunk_chunk_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptionjob',
            name='whisper_size',
            field=models.CharField(choices=[('MEDIUM', 'Medium'), ('TINY', 'Tiny'), ('BASE', 'Base'), ('SMALL', 'Small'), ('LARGE_V3', 'Large V3')], default='SMALL', max_length=15),
        ),
    ]
