# Generated by Django 5.1.1 on 2024-11-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_message_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='background_image_src',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
