# Generated by Django 5.1.1 on 2025-12-09 21:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_layers', '0018_alter_languagemodel_pricing'),
        ('authenticate', '0009_featureflag_featureflagassignment'),
        ('messaging', '0008_chatwidget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pending_analysis',
            field=models.BooleanField(default=False, help_text='Indica si la conversación tiene un análisis pendiente de procesar'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='summary',
            field=models.TextField(blank=True, help_text='Resumen de la conversación generado por la IA', null=True),
        ),
        migrations.CreateModel(
            name='ConversationAlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre de la regla de alerta', max_length=50)),
                ('trigger', models.TextField(help_text='Explicación de los parámetros que deben cumplirse para levantar esta alerta')),
                ('extractions', models.JSONField(blank=True, default=dict, help_text='Los datos que la IA debe extraer de la conversación (ej: Nombre, fecha, problema, etc)')),
                ('scope', models.CharField(choices=[('all_conversations', 'All Conversations'), ('selected_agents', 'Selected Agents')], default='all_conversations', help_text='A qué conversaciones o agentes aplica esta regla', max_length=20)),
                ('enabled', models.BooleanField(default=True, help_text='Si esta regla está activada o no')),
                ('notify_to', models.CharField(choices=[('all_staff', 'All Staff'), ('selected_members', 'Selected Members')], default='all_staff', help_text='A quién notificar cuando se active esta alerta', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agents', models.ManyToManyField(blank=True, help_text="Agentes seleccionados (solo aplica si scope='selected_agents')", related_name='alert_rules', to='ai_layers.agent')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó esta regla', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alert_rules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organización a la que pertenece esta regla', on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='authenticate.organization')),
                ('selected_members', models.ManyToManyField(blank=True, help_text="Miembros seleccionados para notificar (solo aplica si notify_to='selected_members')", related_name='subscribed_alert_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation Alert Rule',
                'verbose_name_plural': 'Conversation Alert Rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Título de la alerta (creado por la IA)', max_length=50)),
                ('reasoning', models.TextField(help_text='Explicación de la IA de por qué se levantó esta alerta')),
                ('extractions', models.JSONField(blank=True, default=dict, help_text='Extracción de datos de la IA: JSON que contiene los datos extraídos de la conversación')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('NOTIFIED', 'Notified'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING', help_text='Estado de la alerta', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(help_text='Conversación que generó esta alerta', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='messaging.conversation')),
                ('dismissed_by', models.ForeignKey(blank=True, help_text='Usuario que desechó esta alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Usuario que resolvió esta alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('alert_rule', models.ForeignKey(help_text='Regla que generó esta alerta', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='messaging.conversationalertrule')),
            ],
            options={
                'verbose_name': 'Conversation Alert',
                'verbose_name_plural': 'Conversation Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Usuario suscrito a esta alerta', on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('alert_rule', models.ForeignKey(help_text='Regla de alerta a la que el usuario se está suscribiendo', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='messaging.conversationalertrule')),
            ],
            options={
                'verbose_name': 'Alert Subscription',
                'verbose_name_plural': 'Alert Subscriptions',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'alert_rule')},
            },
        ),
    ]
