# Generated by Django 5.1.1 on 2026-02-14 05:57

import api.messaging.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_layers', '0022_agentsession'),
        ('messaging', '0013_conversation_organization_alter_conversation_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='message_attachments/%Y/%m/')),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('expires_at', models.DateTimeField(default=api.messaging.models._message_attachment_expires_default, help_text='After this date the attachment can be deleted (default: 30 days)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_attachments', to='ai_layers.agent')),
                ('conversation', models.ForeignKey(help_text='Conversation context; required when uploading before message exists', on_delete=django.db.models.deletion.CASCADE, related_name='message_attachments', to='messaging.conversation')),
                ('message', models.ForeignKey(blank=True, help_text='The message this attachment belongs to (set when message is created)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_files', to='messaging.message')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
