# Generated by Django 5.1.1 on 2026-02-19 04:15

import api.messaging.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0014_messageattachment'),
        ('rag', '0008_document_total_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='kind',
            field=models.CharField(choices=[('file', 'File'), ('rag_document', 'RAG Document'), ('website', 'Website')], default='file', help_text='Attachment kind: file upload, RAG document reference, or website reference', max_length=20),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='rag_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_attachments', to='rag.document'),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=api.messaging.models._message_attachment_expires_default, help_text='After this date the attachment can be deleted (default: 30 days)', null=True),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message_attachments/%Y/%m/'),
        ),
    ]
