# Generated by Django 5.1.1 on 2026-02-25 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0015_messageattachment_kind_messageattachment_metadata_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WidgetVisitorSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("visitor_id", models.CharField(db_index=True, max_length=64)),
                ("origin", models.CharField(blank=True, default="", max_length=255)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("expires_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("is_blocked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "widget",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="visitor_sessions", to="messaging.chatwidget"),
                ),
            ],
            options={
                "unique_together": {("widget", "visitor_id")},
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="chat_widget",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="conversations", to="messaging.chatwidget"),
        ),
        migrations.AddField(
            model_name="conversation",
            name="widget_visitor_session",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="conversations", to="messaging.widgetvisitorsession"),
        ),
    ]
