# Generated by Django 5.1.1 on 2026-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0017_conversation_status_lifecycle_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatwidget",
            name="style",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
