# Generated by Django 5.1.1 on 2026-05-21 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0023_organizationmanagementproxy'),
        ('messaging', '0024_whatsapp_conversation_fields'),
        ('whatsapp', '0012_remove_legacy_whatsapp_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='uniq_whatsapp_thread',
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('ws_number__isnull', False), ('whatsapp_user_number__isnull', False)), fields=('ws_number', 'whatsapp_user_number'), name='uniq_whatsapp_thread'),
        ),
    ]
