# Generated by Django 5.1.1 on 2026-07-21 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0025_organizationtenant'),
        ('messaging', '0029_chatwidget_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledConversationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instruction_text', models.TextField(help_text='Imperative task text injected as a user message when the schedule fires.')),
                ('schedule_type', models.CharField(choices=[('once', 'Once'), ('recurring', 'Recurring')], max_length=16)),
                ('timezone', models.CharField(help_text='IANA timezone snapshot used for wall-clock scheduling.', max_length=50)),
                ('run_at', models.DateTimeField(blank=True, help_text='UTC instant for one-off schedules.', null=True)),
                ('recurrence', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=16, null=True)),
                ('time_of_day', models.CharField(blank=True, help_text='Local HH:MM for structured recurrence.', max_length=5, null=True)),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='Weekdays for weekly recurrence: 0=Mon … 6=Sun.')),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cron', models.CharField(blank=True, help_text='Optional 5-field cron in organization timezone.', max_length=64, null=True)),
                ('next_run_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('agent_slugs', models.JSONField(blank=True, default=list)),
                ('multiagentic_modality', models.CharField(default='isolated', max_length=32)),
                ('created_message_id', models.IntegerField(blank=True, help_text='Last user Message id created when this schedule fired.', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='messaging.conversation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_conversation_tasks', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_conversation_tasks', to='authenticate.organization')),
            ],
            options={
                'ordering': ['next_run_at'],
                'indexes': [models.Index(fields=['status', 'next_run_at'], name='messaging_s_status_6faa13_idx'), models.Index(fields=['conversation', 'status'], name='messaging_s_convers_0b483a_idx')],
            },
        ),
    ]
