# Generated by Django 5.1.1 on 2026-07-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0030_scheduled_conversation_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledconversationtask',
            name='capabilities',
            field=models.JSONField(blank=True, default=list, help_text='Snapshot of enabled tool names from the scheduling turn. Used as the capability override when the task fires.'),
        ),
    ]
