# Generated by Django 5.1.1 on 2026-08-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0033_scheduled_conversation_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledconversationtask',
            name='capabilities',
            field=models.JSONField(blank=True, default=list, help_text='Optional tool allowlist for execution. Empty means all available tools; non-empty constrains the scheduled run to those tool names.'),
        ),
    ]
