# Generated by Django 5.1.1 on 2026-07-10 01:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0025_organizationtenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('elevenlabs', 'ElevenLabs')], max_length=32)),
                ('provider_voice_id', models.CharField(max_length=255)),
                ('scope', models.CharField(choices=[('system', 'System'), ('organization', 'Organization'), ('user', 'User')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voices', to='authenticate.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_voices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scope', 'name'],
                'constraints': [models.UniqueConstraint(fields=('scope', 'organization', 'user', 'provider', 'provider_voice_id'), name='voices_voice_unique_per_scope_owner')],
            },
        ),
    ]
