# Generated by Django 5.1.1 on 2024-10-07 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('rag', '0003_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.conversation'),
        ),
    ]
