# Generated by Django 5.1.1 on 2024-10-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0005_alter_collection_chunk_overlap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
