# Generated by Django 5.1.1 on 2024-10-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0006_chunk_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='brief',
            field=models.TextField(blank=True, null=True),
        ),
    ]
