# Generated by Django 5.1.1 on 2024-10-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_layers', '0002_agent_is_public_agent_user_alter_agent_act_as_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='system_prompt',
            field=models.TextField(default='\n{{act_as}}\n\nThe following context may be useful for your task:\n```\n{{context}}\n```\n'),
        ),
    ]
