# Generated by Django 5.1.1 on 2024-10-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_layers', '0005_languagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
