# Generated by Django 5.1.1 on 2024-11-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_layers', '0009_agent_llm'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
