# Generated by Django 5.1.1 on 2024-11-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_layers', '0012_agent_openai_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
