# Generated by Django 5.1.1 on 2024-12-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_layers', '0014_alter_agent_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='profile_picture_src',
            field=models.TextField(blank=True, null=True),
        ),
    ]
