# Generated by Django 5.1.1 on 2024-12-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_layers', '0015_agent_profile_picture_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagemodel',
            name='pricing',
            field=models.JSONField(default={'text': {'output': '10 USD / 1M', 'prompt': '2.50 USD / 1M'}}),
        ),
    ]
