# Generated by Django 5.1.1 on 2024-12-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_layers', '0016_languagemodel_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagemodel',
            name='pricing',
            field=models.JSONField(default=dict),
        ),
    ]
