# Generated by Django 5.1.1 on 2024-10-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finetuning', '0006_alter_traininggenerator_generation_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininggenerator',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
