# Generated by Django 5.1.1 on 2024-12-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_userpreferences_multiagentic_modality'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='background_image_opacity',
            field=models.FloatField(default=0.5),
        ),
    ]
