# Generated by Django 5.1.1 on 2026-02-10 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0007_webpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTags',
        ),
    ]
