# Generated by Django 5.1.1 on 2024-11-03 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_reactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reactions',
        ),
    ]
