# Generated by Django 5.1.1 on 2024-11-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_sharedconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='agents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
