# Generated by Django 5.1.1 on 2026-01-02 16:05
# Modified to add field if missing instead of altering

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_tag_and_conversation_tags_migration'),
    ]

    operations = [
        # Primero, actualizar el estado del modelo en Django
        migrations.AlterField(
            model_name='conversation',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Lista de IDs de tags asociadas a esta conversación (solo tags habilitadas)'),
        ),
        # Luego, usar RunSQL para asegurar que la columna existe en la BD
        migrations.RunSQL(
            sql="""
                ALTER TABLE messaging_conversation 
                ADD COLUMN IF NOT EXISTS tags JSONB DEFAULT '[]'::jsonb;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
