"""Platform-wide data governance limits."""

MIN_ATTACHMENT_RETENTION_DAYS = 7
MIN_DELETED_CONVERSATION_RETENTION_DAYS = 0

EXPORT_FILE_TTL_DAYS = 7
EXPORT_MAX_DOWNLOAD_COUNT = 3
EXPORT_MAX_DATE_RANGE_DAYS = 365
