# Generated by Django 5.1.1 on 2026-08-20 02:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0026_userprofile__phone_numbers'),
        ('messaging', '0036_messageattachment_visibility_db_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('mifiel', 'Mifiel')], default='mifiel', max_length=32)),
                ('provider_document_id', models.CharField(blank=True, default='', help_text='Document id returned by the provider (e.g. Mifiel document uuid).', max_length=255)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Masscer-generated correlation id sent to the provider as external_id. Used to match inbound webhooks to this request without trusting the webhook payload alone.', unique=True)),
                ('document_kind', models.CharField(choices=[('internal_policy_manual', 'Manual de politicas internas'), ('risk_methodology', 'Metodologia EBR'), ('kyc_file', 'Expediente KYC/KYB'), ('suspicious_activity_notice', 'Aviso de 24 horas'), ('monthly_notice', 'Aviso mensual'), ('other', 'Otro')], default='other', max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('signatory_name', models.CharField(max_length=255)),
                ('signatory_email', models.EmailField(max_length=254)),
                ('signatory_rfc', models.CharField(blank=True, default='', max_length=13)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de firma'), ('signed', 'Firmado'), ('rejected', 'Rechazado'), ('expired', 'Expirado'), ('deleted', 'Eliminado'), ('error', 'Error')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Free-form provider response snapshots, error details, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='authenticate.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_requests_created', to=settings.AUTH_USER_MODEL)),
                ('signatory_user', models.ForeignKey(blank=True, help_text='Internal user who must sign, when they have a Masscer account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_requests_to_sign', to=settings.AUTH_USER_MODEL)),
                ('signed_file', models.ForeignKey(blank=True, help_text='Signed PDF, attached back to the source conversation after document_closed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_requests_as_signed_pdf', to='messaging.messageattachment')),
                ('signed_file_xml', models.ForeignKey(blank=True, help_text='Legally-binding XML (with NOM-151 conservation record), attached after document_closed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_requests_as_signed_xml', to='messaging.messageattachment')),
                ('source_file', models.ForeignKey(help_text='Unsigned PDF sent to the provider, as already generated/uploaded in a conversation.', on_delete=django.db.models.deletion.PROTECT, related_name='signature_requests_as_source', to='messaging.messageattachment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureRequestEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text='Raw provider event name, e.g. document_closed, signer_completed.', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('signature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='esign.signaturerequest')),
            ],
            options={
                'ordering': ['received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='signaturerequest',
            index=models.Index(fields=['organization', 'status'], name='esign_signa_organiz_03cbab_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturerequest',
            index=models.Index(fields=['provider', 'provider_document_id'], name='esign_signa_provide_dd360b_idx'),
        ),
        migrations.AddIndex(
            model_name='signaturerequestevent',
            index=models.Index(fields=['signature_request', 'event_type'], name='esign_signa_signatu_453578_idx'),
        ),
    ]
