# Generated by Django 5.1.1 on 2026-08-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturerequest',
            name='provider_widget_id',
            field=models.CharField(blank=True, default='', help_text="Mifiel's per-signer widget_id (signers[0].widget_id from create_document), used to render the embeddable <mifiel-widget> for this signatory. Empty until submit_signature_request_to_mifiel completes.", max_length=64),
        ),
    ]
