# Generated by Django 5.1.1 on 2026-10-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0005_jaakwebhookinbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturerequest',
            name='provider',
            field=models.CharField(choices=[('mifiel', 'Mifiel'), ('jaak', 'Jaak')], default='mifiel', max_length=32),
        ),
    ]
