# Generated by Django 5.1.1 on 2025-01-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComputeUnit',
            new_name='Currency',
        ),
    ]
