# Generated by Django 5.1.1 on 2024-10-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_wsmessage_collected_info_wsmessage_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsconversation',
            name='sentiment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wsconversation',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
