# Generated by Django 5.1.1 on 2026-03-23 21:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0018_userprofile_is_active'),
        ('consumption', '0003_alter_consumption_amount_alter_wallet_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='authenticate.organization')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumption.currency')),
            ],
        ),
    ]
