# Generated by Django 5.1.1 on 2026-03-26 02:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0004_organizationwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=0.1, max_digits=20),
        ),
        migrations.AlterField(
            model_name='organizationwallet',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
