# Generated by Django 5.1.1 on 2026-05-21 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0006_organizationwallet_split_and_ledger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationwallet',
            options={'verbose_name': 'Organization wallet', 'verbose_name_plural': 'Organization wallets'},
        ),
        migrations.RenameIndex(
            model_name='organizationwallettransaction',
            new_name='consumption_organiz_63844a_idx',
            old_name='consumption_wtx_org_crt',
        ),
    ]
