# Generated by Django 5.1.1 on 2024-11-03 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        ('messaging', '0003_message_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.message'),
        ),
    ]
