# Generated by Django 5.1.1 on 2024-10-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_wsconversation_sentiment_wsconversation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='wscontact',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wscontact',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='wscontact',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
