# Generated by Django 5.1.1 on 2024-10-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_wsconversation_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsmessage',
            name='message_platform_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
