# Generated by Django 5.1.1 on 2024-10-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0009_alter_wsmessage_message_platform_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsnumber',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
