# Generated by Django 5.1.1 on 2026-06-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0014_wsnumber_waba_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wsnumber',
            name='number',
            field=models.CharField(help_text='Phone number in any format — spaces, dashes, parentheses and + are stripped automatically.', max_length=30),
        ),
    ]
