# Generated by Django 5.1.1 on 2026-08-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0026_userprofile__phone_numbers'),
        ('whatsapp', '0018_wstemplate_and_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wsnumber',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, help_text='When access_mode=roles, members with any of these roles may message. The organization owner always has access.', related_name='whatsapp_numbers_with_access', to='authenticate.role'),
        ),
    ]
