# Generated by Django 5.1.1 on 2024-09-30 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('ERROR', 'Error')], default='PENDING', max_length=7)),
                ('status_text', models.TextField()),
                ('source_type', models.CharField(choices=[('YOUTUBE_URL', 'YouTube URL'), ('AUDIO', 'Audio'), ('VIDEO', 'Video')], max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, max_length=255, null=True, upload_to='audio_files/')),
                ('video_file', models.FileField(blank=True, max_length=255, null=True, upload_to='video_files/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('VTT', 'VTT')], default='VTT', max_length=3)),
                ('result', models.TextField()),
                ('language', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcription_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='tools.transcriptionjob')),
            ],
        ),
    ]
