# Generated by Django 5.1.1 on 2024-09-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptionjob',
            name='audio_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='audio_files/'),
        ),
    ]
