# Generated by Django 5.1.1 on 2024-09-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_transcriptionjob_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionjob',
            name='video_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='video_files/'),
        ),
        migrations.AlterField(
            model_name='transcriptionjob',
            name='source_type',
            field=models.CharField(choices=[('YOUTUBE_URL', 'YouTube URL'), ('AUDIO', 'Audio'), ('VIDEO', 'Video')], max_length=11),
        ),
    ]
