# Generated by Django 5.1.1 on 2024-09-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_transcriptionjob_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionjob',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
