# Generated by Django 5.1.1 on 2026-03-18 23:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0018_userprofile_is_active'),
        ('messaging', '0019_chatwidget_capabilities_first_message'),
        ('notify', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conditions', models.JSONField(default=list, help_text='List of condition objects. Each must match the NotificationCondition schema. Example: [{"subject": "n_alerts", "condition": "n_alerts > 5", "delivery_method": "app", "message": "{{n_alerts}} pending alerts!"}]')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='messaging.conversationalertrule')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_rules', to=settings.AUTH_USER_MODEL)),
                ('notify_to_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules_as_target', to='authenticate.organization')),
                ('notify_to_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='authenticate.role')),
                ('notify_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='authenticate.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_method', models.CharField(choices=[('app', 'App'), ('email', 'Email'), ('all', 'All')], default='app', max_length=10)),
                ('message', models.TextField()),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the notification was actually sent/delivered to the user.', null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('ignored_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='messaging.conversationalert')),
                ('notification_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='notify.notificationrule')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='authenticate.organization')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
