# Generated by Django 5.1.1 on 2024-11-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_remove_organization_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=40, unique=True),
        ),
    ]
