# Generated by Django 5.1.1 on 2025-01-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_alter_userprofile_age_alter_userprofile_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialsmanager',
            name='elevenlabs_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='credentialsmanager',
            name='heygen_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
