# Generated by Django 5.1.1 on 2026-01-06 21:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0014_organization_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the role', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of the role', null=True)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this role exists under the organization or not')),
                ('capabilities', models.JSONField(blank=True, default=list, help_text='List of feature flag slugs that this role will have enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(help_text='Organization this role belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='authenticate.organization')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_date', models.DateField(help_text='Date from which the user has this role')),
                ('to_date', models.DateField(blank=True, help_text='Date until which the user has this role. Empty if the role is active or has no end date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(help_text='Organization this assignment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='authenticate.organization')),
                ('role', models.ForeignKey(help_text='Role being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='authenticate.role')),
                ('user', models.ForeignKey(help_text='User to whom the role is assigned', on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Assignment',
                'verbose_name_plural': 'Role Assignments',
                'indexes': [models.Index(fields=['user', 'organization'], name='authenticat_user_id_b3506a_idx'), models.Index(fields=['from_date', 'to_date'], name='authenticat_from_da_5014be_idx')],
            },
        ),
    ]
