# Generated by Django 5.1.1 on 2026-02-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0016_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflag',
            name='organization_only',
            field=models.BooleanField(default=False, help_text='If True, this flag can only be assigned at the organization level (not to users or as role capabilities).'),
        ),
    ]
