# Generated by Django 5.1.1 on 2026-03-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0018_userprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=None, help_text="If set, the user's access expires at this datetime. Useful for temporary guest accounts.", null=True),
        ),
    ]
