# Generated by Django 5.1.1 on 2026-05-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0021_organizationinvite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organizationinvite',
            new_name='authenticat_organiz_96db20_idx',
            old_name='authentica_organiz_a772fc_idx',
        ),
        migrations.AlterField(
            model_name='organizationinvite',
            name='profile_expires_at',
            field=models.DateTimeField(blank=True, help_text='Prefilled membership expiry on UserProfile when invite is accepted.', null=True),
        ),
    ]
