# Generated by Django 5.1.1 on 2026-05-11 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0022_rename_authentica_organiz_a772fc_idx_authenticat_organiz_96db20_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationManagementProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Organizations Management',
                'verbose_name_plural': 'Organizations Management',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authenticate.organization',),
        ),
    ]
